addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

# new options suggested by Alexandre Fayolle
# sudo: false
cache: pip

python:
  - "2.7"

env:
  # - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  # we install libcups2-dev here because it is not on travis whitelist so it is not installable by addons/apt/packages
  # you can check if available on https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcups2-dev
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68
  - pip install python-ldap

  # odoo addons web
  - git clone https://github.com/ingadhoc/odoo-web.git -b 8.0 ${HOME}/odoo-web

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git -b 8.0 ${HOME}/odoo-addons

  # odoo argentina
  # TODO change to 8.0 when ready
  - git clone https://github.com/ingadhoc/odoo-argentina.git -b 8.0 ${HOME}/odoo-argentina
  - pip install geopy==0.95.1 BeautifulSoup 

  # oca server tools
  - git clone https://github.com/OCA/server-tools.git ${HOME}/server-tools
  # oca commission
  - git clone https://github.com/OCA/commission.git ${HOME}/commission
  # oca partner-contact
  - git clone https://github.com/OCA/partner-contact.git ${HOME}/partner-contact

  # for odoo pdf reports (tested on sale for eg.)
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
