addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - libcups2-dev # for aeroo
      - wkhtmltopdf # for odoo pdf reports (tested on sale for eg.)
      # FE for scanterar
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2

language: python
sudo: false
cache: pip

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: m+pWY35/CMpBD3Ka2sWc6KoNo+7HQ+JkwtqwnUqsHp2/131dJ7kzZ1OxvJ3RYqJhlRJr6e3dvbMbp18yYzaWDGT0mx4pZvvIeFO8QMzoC0J6xSIaXA7w2jvtpOqeROnPCzFS/J0c9t892g6xOKIj8/pEntWBobVSMKj+vOeyxWTQ+cDIdTjJlZidLBujvwCJHSLpg14FgQpBdGqPTem5f0t+zxt2osNB9ckedakRdevj5DlBLxstMRKRnAuf97i3FG5OkH/DpldocYz2XZYDgfe1V+YazCDdUR2FqPYW2PziQXR96DgX7L0SDUhbgZVT7vQSC3uvahicungtrSx/hZaxag7GbHWIFzODX4LIUIQ4C8ivc8wi3bU44FC3Vyh7lnBfDQW+xUncaXpmMR0kdP/fU2ZC/s3n3yAf97xC6lH2KS0oq1WXDcLtrcuxsvYzZ2XYm8K+fSJdCqhXKfd7onioFSgN8ulsCDMUReaBegEQzqBlde1qqh8Kq326TQKT1RhcX0knIng2sHqDhdgFRczktnSYXtGyUChps7C8IJtN/O7G8c4iOqaXcJu1GkJ/qtnxgaCzPkTPwrfnRPJg0VXK/gZduRhO0LQDxaplM7S/lGGKflbTUj/39W9M0I3r7dJvJxRxw8cftbFRYwbJhto6PugNS7W+P3ONhUbow4o=

  matrix:
  # TODO habilitar
  - LINT_CHECK="0"
  # TODO arreglar e incluir transindar_personalization (no anda ni si quiera solo)
  - TRANSIFEX="1" EXCLUDE="transindar_personalization"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="transindar_personalization"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo addons web
  - git clone https://github.com/ingadhoc/odoo-web.git -b 8.0 ${HOME}/odoo-web

  # odoo help
  - git clone https://github.com/ingadhoc/odoo-help.git -b 8.0 ${HOME}/odoo-help

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git -b 8.0 ${HOME}/odoo-addons

  # odoo argentina
  # TODO change to 8.0 when ready
  - git clone https://github.com/ingadhoc/odoo-argentina.git ${HOME}/odoo-argentina -b ${VERSION}
  - pip install geopy==0.95.1 BeautifulSoup #because l10n_ar_states is installed
  # for scanterra fe
  - pip install pyOpenSSL suds m2crypto cryptography pysimplesoap fpdf dbf Pillow
  - pip install pyafipws

  # oca server tools
  - pip install python-ldap
  - git clone https://github.com/OCA/server-tools.git ${HOME}/server-tools -b ${VERSION}

  # oca commission
  - git clone https://github.com/OCA/commission.git ${HOME}/commission -b ${VERSION}

  # oca partner-contact
  - git clone https://github.com/OCA/partner-contact.git ${HOME}/partner-contact -b ${VERSION}

  # oca product-attribute
  - git clone https://github.com/OCA/product-attribute.git ${HOME}/product-attribute -b ${VERSION}

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
